# 서버 포트 설정
# 접속: http://localhost:8081
server:
  port: 8081

#비밀키 (base64로 인코딩하여 설정파일에 저장)
jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo0MTEyMjMzNA==

# database 연동 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_sst?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_sst
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # create or update
    show-sql: true  # SQL 실행 로그 출력